### ISSUE TITLE
Can't convert KIDA 2014 network to Astrochem format

### ISSUE THREAD

**Issue by BhaswatiMookerjea** [smaret/astrochem#48]
Using astrochem-0.7 I tried to convert the latest KIDA datafiles to the astrochem format, but got the error

`chmconvert_local: incorrect input on line 1.`

I copied the kida.uva.2014.dat file to kidauva2014.kida and then gave the following command:

`chmconvert -o try.chm kidauva2014.kida`

**Comment by smaret** [comment]
The KIDA 2014 file format isn't supported yet. See PR #38 for more information.
