### ISSUE TITLE
Python interface and command line give different results

### ISSUE THREAD

**Issue by smaret** [smaret/astrochem#53]
Astrochem Python interface give different results that the command line for this [model](https://gist.github.com/smaret/d4d99eca2ef657f6d3471ba4bae9b8ae).
![cl_vs_python](https://cloud.githubusercontent.com/assets/95471/16732286/af5699c8-477c-11e6-9dc8-12fff21e53f7.png)
The results are identical if the cosmic-ray ionization rate is set to it default value, so I suspect that some the parameters are ignored by the Python interface.

**Comment by smaret** [comment]
CC @BhaswatiMookerjea

**Comment by smaret** [comment]
Results also differ for `chi=100` and a visual extinction of 1. All parameters/members of the Python `phys` object are probably ignored.

@mwestphal: any thought?

**Comment by smaret** [comment]
This is fact quite simple. `phys` is a Python wrapper around the `libpyastrochem.Phys` object. When `phys` is instantiated for the first time, its attributes are copied from `libpyastrochem.Phys`:

```python
def __init__(self):
        
    self.data = libpyastrochem.Phys()
    self.chi  = self.data.chi
    self.cosmic = self.data.cosmic
    self.grain_abundance = self.data.grain_abundance
    self.grain_size = self.data.grain_size
```

but then when the attributes are updated, the new values aren't modified in the corresponding `libpyastrochem.Phys` object:

```python
from astrochem.wrapper import *
p = phys()
p.chi = 200
print(p.chi)
>>> print(p.chi)
200
print(p.chi.data)
>>> print(p.data.chi)
1.0
```

If one sets `p.data.chi = 200`, both Python and command line interfaces give the same results.

**Comment by mwestphal** [comment]
sorry i missed your ping. nice fix.
