### ISSUE TITLE
Problems with "libpyastrochem.la" and non-root installation

### ISSUE THREAD

**Issue by johnilee** [smaret/astrochem#56]
I'm trying to install astrochem on my workstation (which unfortunately doesn't have root privileges).  I've followed the ./configure -- prefix=... route, but on "make install" I'm presented with the following error... 

```
make[3]: Entering directory `/data/vault/jdilee/astrochem_tar/astrochem-0.7/python/libpyastrochem'
 /bin/mkdir -p '/data/vault/jdilee/astrochem_tar/astrochem-0.7/lib/python2.7/site-packages/astrochem'
 /bin/sh ../../libtool   --mode=install /usr/bin/install -c   libpyastrochem.la '/data/vault/jdilee/astrochem_tar/astrochem-0.7/lib/python2.7/site-packages/astrochem'
 libtool:   error: error: cannot install 'libpyastrochem.la' to a directory not ending in /usr/local/lib/python2.7/site-packages/astrochem
 make[3]: *** [install-pkgpyexecLTLIBRARIES] Error 1
```

Is the installer hard coded to assume I have write access to /usr/local/lib/?  Unfortunately this is not the case.

Any help greatly appreciated,
John

**Comment by smaret** [comment]
Is your build directory clean? This kind of errors can occur if you make a first build without `--prefix` before installation. Try to run `configure --prefix=... && make clean && make && make install`, or start over from a fresh distribution tarball.

**Comment by smaret** [comment]
Did it solve your issue?

**Comment by smaret** [comment]
I'm closing this issue due to lack of response. Please feel free to reopen this issue if needed.
