### ISSUE TITLE
Compiling issue with typedef enum

### ISSUE THREAD

**Issue by diskmodeling** [smaret/astrochem#68]
After running configure, I get the following errors when I try to compile.  I'm not sure what is wrong with the typedef enum statement in libastrchem.h.  Any ideas on what may be the issue?

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..    -DPKGDATADIR=\"/usr/local/share/astrochem\"  -Wall -g -O2 -MT network.lo -MD -MP -MF .deps/network.Tpo -c -o network.lo network.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -DPKGDATADIR=\"/usr/local/share/astrochem\" -Wall -g -O2 -MT network.lo -MD -MP -MF .deps/network.Tpo -c network.c  -fno-common -DPIC -o .libs/network.o
In file included from network.c:30:
In file included from ./astrochem.h:28:
./libastrochem.h:84:16: error: expected identifier
typedef enum { false, true } bool;
               ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/include/stdbool.h:33:15: note: 
      expanded from macro 'false'
#define false 0
              ^
In file included from network.c:30:
In file included from ./astrochem.h:28:
./libastrochem.h:84:23: error: expected identifier
typedef enum { false, true } bool;
                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/include/stdbool.h:32:14: note: 
      expanded from macro 'true'
#define true 1
             ^
In file included from network.c:30:
In file included from ./astrochem.h:28:
./libastrochem.h:84:29: error: expected ';' after enum
typedef enum { false, true } bool;
                            ^
                            ;
./libastrochem.h:84:1: warning: typedef requires a name [-Wmissing-declarations]
typedef enum { false, true } bool;
^~~~~~~
./libastrochem.h:84:30: warning: declaration does not declare anything [-Wmissing-declarations]
typedef enum { false, true } bool;
                             ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/include/stdbool.h:31:14: note: 
      expanded from macro 'bool'
#define bool _Bool
             ^~~~~
2 warnings and 3 errors generated.
make[2]: *** [network.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
bash-3.2$ 
```

**Comment by smaret** [comment]
I think @cpinte has bumped into a similar error but I could not reproduce it. Which versions of XCode and MacOS are you running @diskmodeling ?

**Comment by diskmodeling** [comment]
I have MacOS Sierra 10.12.3 and Xcode 8.2.1.  I tried a different compiler--upgrading to gcc-6 and using that and got a slightly different version of the error:


bash-3.2$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
/bin/sh ../libtool  --tag=CC   --mode=compile /usr/local/Cellar/gcc/6.3.0_1/bin/gcc-6 -DHAVE_CONFIG_H -I. -I..    -DPKGDATADIR=\"/usr/local/share/astrochem\"  -Wall -g -O2 -MT network.lo -MD -MP -MF .deps/network.Tpo -c -o network.lo network.c
libtool: compile:  /usr/local/Cellar/gcc/6.3.0_1/bin/gcc-6 -DHAVE_CONFIG_H -I. -I.. -DPKGDATADIR=\"/usr/local/share/astrochem\" -Wall -g -O2 -MT network.lo -MD -MP -MF .deps/network.Tpo -c network.c  -fno-common -DPIC -o .libs/network.o
In file included from /usr/local/include/H5public.h:145:0,
                 from /usr/local/include/hdf5.h:24,
                 from astrochem.h:27,
                 from network.c:30:
libastrochem.h:84:16: error: expected identifier before numeric constant
 typedef enum { false, true } bool;
                ^
libastrochem.h:84:30: error: expected ';', identifier or '(' before '_Bool'
 typedef enum { false, true } bool;
                              ^
make[2]: *** [network.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
bash-3.2$

**Comment by smaret** [comment]
How do you invoke `configure` exactly? I see that you have `homebrew` installed, do you have `macports` as well (the two can conflict at times).

**Comment by diskmodeling** [comment]
I do have both homebrew and macports.  Perhaps that is the issue.  I configured with just:

./configure CC=gcc // the first time
./configure CC=/pointtobrew/gcc-6 the second time

Should I set more flags for fortran and python to avoid confusion?

**Comment by smaret** [comment]
Could you please try to move the macport directory out of the way:
```
sudo mv /opt/local /opt/local.moved
```

and then compile `astrochem` following the instructions on the [wiki page](https://github.com/smaret/astrochem/wiki)? You may need to run a `make clean` after `configure`.

**Comment by diskmodeling** [comment]
I tried this and it gives me the same error as before (see below, with the summary of the configure information).  I did not make gcc-6 my default and explicitly point to the compiler in the directory where it was stored by brew.  Let me know if that could be a problem.

I'll keep on trying on my end here and try installing it on a different computer to see if that gets me anywhere.  Please let me know if you have any other suggestions.

=============================================
Configuration summary:
C compiler:         /usr/local/Cellar/gcc/6.3.0_1/bin/gcc-6 -g -O2
OpenMP support:     no
LAPACK support:     no
Python interpreter: /usr/local/Cellar/python/2.7.13/bin/python2.7
Python version:     2.7
Biggles module:     no
H5py module:        yes
Python API:         yes
=============================================
bash-3.2$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
/bin/sh ../libtool  --tag=CC   --mode=compile /usr/local/Cellar/gcc/6.3.0_1/bin/gcc-6 -DHAVE_CONFIG_H -I. -I..    -DPKGDATADIR=\"/usr/local/share/astrochem\"  -Wall -g -O2 -MT network.lo -MD -MP -MF .deps/network.Tpo -c -o network.lo network.c
libtool: compile:  /usr/local/Cellar/gcc/6.3.0_1/bin/gcc-6 -DHAVE_CONFIG_H -I. -I.. -DPKGDATADIR=\"/usr/local/share/astrochem\" -Wall -g -O2 -MT network.lo -MD -MP -MF .deps/network.Tpo -c network.c  -fno-common -DPIC -o .libs/network.o
In file included from /usr/local/include/H5public.h:145:0,
                 from /usr/local/include/hdf5.h:24,
                 from astrochem.h:27,
                 from network.c:30:
libastrochem.h:84:16: error: expected identifier before numeric constant
 typedef enum { false, true } bool;
                ^
libastrochem.h:84:30: error: expected ';', identifier or '(' before '_Bool'
 typedef enum { false, true } bool;
                              ^
make[2]: *** [network.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
bash-3.2$

**Comment by smaret** [comment]
OK, I've spotted the issue. The HDF5 library defines its own boolean type, which conflicts with the one we define in `astrochem`.

**Comment by smaret** [comment]
Fixed! Thanks for reporting this error.

And please contact me by email if you intend to do some disk modelling with astrochem as your login name suggests. I've made some recent developments in astrochem  that aren't public yet and that could be of interest to you.
