### ISSUE TITLE
Installation on ubuntu using anaconda

### ISSUE THREAD

**Issue by christer-watson** [smaret/astrochem#83]
I ran into trouble installing astrochem under ubuntu (18.04 LTS) and anaconda. I followed the Mac instructions, which appeared to execute without errors. Within the python command line, however, I have the following behavior:

```python
import astrochem
  File "/home/christer_watson/anaconda3/envs/astrochem/lib/python3.7/site-packages/astrochem/__init__.py", line 12, in <module>
    import tools
ModuleNotFoundError: No module named 'tools'
```

I think the problem is that python now expects absolute paths in the __init__.py module. I edited that module to read (in part):

```python
try:
    from . import libpyastrochem
    from . import wrapper
except ImportError:
    pass
from . import tools
```

and now `import astrochem` appears to excute without a problem.

**Comment by smaret** [comment]
Thanks for the report and for the fix. Do you want to open a PR with the fix?

**Comment by christer-watson** [comment]
I haven't started my own branch in git-hub before. I guessed how to do it
and made the changes to __init__.py

Cheers,

--Christer

**Comment by smaret** [comment]
OK, I'll merge the fix from your fork then. For next time, you can find instructions on how to open a PR in the [CONTRIBUTING.md](https://github.com/smaret/astrochem/blob/master/CONTRIBUTING.md) file.

Thanks again for the detail report and the fix!
